apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      providers:
        dockerRegistry:
          enabled: true
          accounts:
            name: 123
            requiredGroupMembership: [] # A user must be a member of at least one specified group in order to make changes to this account's cloud resources.
            providerVersion: V1
            permissions: {}
            address: https://123123
            username: 123123123
            password: 123123123123
            email: fake.email@spinnaker.io # Your docker registry email (often this only needs to be well-formed, rather than be a real address)
            cacheIntervalSeconds: 30 # How many seconds elapse between polling your docker registry. Certain registries are sensitive to over-polling, and larger intervals (e.g. 10 minutes = 600 seconds) are desirable if you're seeing rate limiting.
            clientTimeoutMillis: 60000 # Timeout time in milliseconds for this repository.
            cacheThreads: 1 # How many threads to cache all provided repos on. Really only useful if you have a ton of repos.
            paginateSize: 100 # Paginate size for the docker repository _catalog endpoint.
            sortTagsByDate: false # Sort tags by creation date.
            trackDigests: false # Track digest changes. This is not recommended as it consumes a high QPM, and most registries are flaky.
            insecureRegistry: false # Treat the docker registry as insecure (don't validate the ssl cert).
            repositories: 123123123123123

